@startuml
'https://plantuml.com/object-diagram

object "phpDemo1:Folder</u>" as php{
name = "php_demo1"
}
object "<u>Source Files:Folder</u>" as source{
name = "Source Files"
}
object "<u>Include Path:Folder</u>" as include{
name = "Include Path"
}
object "<u>Remote Files:Folder</u>" as remote{
name = "Remote Files"
}

object "<u>.phalcon:Folder</u>" as phalcon{
name = ".phalcon"
}
object "<u>cache:Folder</u>" as cache{
name = "cache"
 }
object "<u>public:Folder</u>" as public{
name = "public"
 }

object "<u>.htaccess:File</u>" as htaccess{
name = ".htaccess"
 }

object "<u>.htrouter.php:File</u>" as htrouter{
 name = ".htrouter.php"
 }
object "<u>index.html:File</u>" as index{
 name = "index.html"
 }

 php *-- source
 php *-- include
 php *-- remote

source *--phalcon
source *-- cache
source *-- public
 public *-- htaccess
 public *-- htrouter
 public *-- index


@enduml
