@startuml
'https://plantuml.com/object-diagram

object "<u>c1:Course</u>" as software{
    name = "CS5800 - Advanced Software Engineering"
}
object "<u>c1Instructor: Instructor </u>" as c1inst{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
 }
object "<u>c1Textbook:Textbook</u>" as c1text{
    author = "Robert Cecil Martin"
    publisher = "Pearson"
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}


software o-- c1inst
software o-- c1text

@enduml
